/**
 * ComponentFactory.tsx - Interactive Component Generation Factory
 * Foundation OS Phase 3 - Live template-driven component creation
 */

import React, { useState } from 'react'

interface Template {
  name: string
  type: string
  description?: string
}

interface ComponentFactoryProps {
  templates: Template[]
  onGenerate: () => void
  generatedCount: number
}

export const ComponentFactory: React.FC<ComponentFactoryProps> = ({
  templates,
  onGenerate,
  generatedCount
}) => {
  const [selectedTemplate, setSelectedTemplate] = useState(templates[0] || null)
  const [customMarkdown, setCustomMarkdown] = useState(`# MyComponent

## Description
A custom component generated from markdown

## Props
- title: string - Component title
- isVisible: boolean - Show/hide component
- onClick: function - Click handler

\`\`\`component MyComponent
description: Interactive component
void-glass: true
\`\`\``)

  const [isGenerating, setIsGenerating] = useState(false)
  const [showPreview, setShowPreview] = useState(false)

  const handleGenerate = async () => {
    setIsGenerating(true)

    // Simulate generation time
    await new Promise(resolve => setTimeout(resolve, 1500))

    onGenerate()
    setIsGenerating(false)
    setShowPreview(true)

    // Hide preview after 3 seconds
    setTimeout(() => setShowPreview(false), 3000)
  }

  const previewCode = `/**
 * ${selectedTemplate?.name || 'MyComponent'}.tsx - Generated Component
 * Auto-generated by Foundation OS Component Factory
 */

import React from 'react'

interface ${selectedTemplate?.name || 'MyComponent'}Props {
  title: string
  isVisible: boolean
  onClick: () => void
}

export const ${selectedTemplate?.name || 'MyComponent'}: React.FC<${selectedTemplate?.name || 'MyComponent'}Props> = ({
  title,
  isVisible,
  onClick
}) => {
  if (!isVisible) return null

  return (
    <div className="bg-black/20 border border-gray-700 rounded-lg p-6">
      <h3 className="text-[#5EEAD4] font-['Figtree'] text-lg mb-2">
        {title}
      </h3>
      <p className="text-gray-300 font-['JetBrains_Mono'] text-sm mb-4">
        Generated by Foundation OS Template Engine
      </p>
      <button
        onClick={onClick}
        className="px-4 py-2 bg-[#5EEAD4] text-[#06070C] rounded font-medium hover:bg-[#4FD1C7] transition-colors"
      >
        Interact
      </button>
    </div>
  )
}

export default ${selectedTemplate?.name || 'MyComponent'}`

  return (
    <div className="bg-black/20 border border-gray-700 rounded-lg p-6">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-[#5EEAD4] font-['Figtree'] text-xl">Component Factory</h3>

        <div className="text-sm text-gray-400 font-['JetBrains_Mono']">
          {generatedCount} components generated
        </div>
      </div>

      {/* Template Selection */}
      <div className="mb-6">
        <h4 className="text-sm font-medium text-gray-300 mb-3 font-['Figtree']">
          Select Template
        </h4>
        <div className="grid grid-cols-1 gap-2">
          {templates.map((template, index) => (
            <button
              key={index}
              onClick={() => setSelectedTemplate(template)}
              className={`p-3 text-left rounded border transition-colors ${
                selectedTemplate?.name === template.name
                  ? 'border-[#5EEAD4] bg-[#5EEAD4]/10'
                  : 'border-gray-600 hover:border-gray-500'
              }`}
            >
              <div className="font-medium text-white font-['Figtree']">
                {template.name}
              </div>
              <div className="text-sm text-gray-400 font-['JetBrains_Mono']">
                Type: {template.type}
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Markdown Input */}
      <div className="mb-6">
        <h4 className="text-sm font-medium text-gray-300 mb-3 font-['Figtree']">
          Markdown Specification
        </h4>
        <textarea
          value={customMarkdown}
          onChange={(e) => setCustomMarkdown(e.target.value)}
          rows={8}
          className="w-full px-3 py-2 bg-gray-900 border border-gray-600 rounded text-white font-['JetBrains_Mono'] text-sm resize-none focus:border-[#5EEAD4] focus:outline-none"
          placeholder="Enter component specification in markdown..."
        />
      </div>

      {/* Generation Controls */}
      <div className="mb-6">
        <button
          onClick={handleGenerate}
          disabled={isGenerating}
          className="w-full px-4 py-3 bg-[#5EEAD4] text-[#06070C] rounded font-medium hover:bg-[#4FD1C7] transition-colors disabled:opacity-50 disabled:cursor-not-allowed font-['Figtree']"
        >
          {isGenerating ? (
            <div className="flex items-center justify-center space-x-2">
              <div className="w-4 h-4 border-2 border-[#06070C] border-t-transparent rounded-full animate-spin" />
              <span>Generating Component...</span>
            </div>
          ) : (
            '🏭 Generate Component from Template'
          )}
        </button>
      </div>

      {/* Live Preview */}
      {showPreview && (
        <div className="mb-6 p-4 bg-green-900/20 border border-green-700 rounded">
          <div className="flex items-center space-x-2 mb-3">
            <div className="w-3 h-3 bg-green-400 rounded-full animate-pulse" />
            <span className="text-green-400 font-medium font-['Figtree']">
              Component Generated Successfully!
            </span>
          </div>

          <div className="bg-gray-900 rounded p-3 border border-gray-600">
            <div className="text-xs text-gray-400 mb-2 font-['JetBrains_Mono']">
              📁 Generated: {selectedTemplate?.name || 'MyComponent'}.tsx
            </div>
            <pre className="text-xs font-['JetBrains_Mono'] text-gray-300 overflow-x-auto max-h-32">
              {previewCode.substring(0, 400)}...
            </pre>
          </div>
        </div>
      )}

      {/* Template Preview */}
      <div className="mb-6">
        <h4 className="text-sm font-medium text-gray-300 mb-3 font-['Figtree']">
          Generated Code Preview
        </h4>
        <div className="bg-gray-900 rounded border border-gray-600 p-4 max-h-64 overflow-y-auto">
          <pre className="text-xs font-['JetBrains_Mono'] text-gray-300">
            {previewCode}
          </pre>
        </div>
      </div>

      {/* Factory Stats */}
      <div className="p-4 bg-gray-900/30 rounded border border-gray-600">
        <h4 className="text-sm font-medium text-gray-300 mb-3 font-['Figtree']">
          Factory Statistics
        </h4>
        <div className="grid grid-cols-3 gap-4 text-center">
          <div>
            <div className="text-lg font-bold text-[#5EEAD4] font-['Figtree']">
              {templates.length}
            </div>
            <div className="text-xs text-gray-400 font-['JetBrains_Mono']">
              Templates
            </div>
          </div>
          <div>
            <div className="text-lg font-bold text-green-400 font-['Figtree']">
              {generatedCount}
            </div>
            <div className="text-xs text-gray-400 font-['JetBrains_Mono']">
              Generated
            </div>
          </div>
          <div>
            <div className="text-lg font-bold text-blue-400 font-['Figtree']">
              100%
            </div>
            <div className="text-xs text-gray-400 font-['JetBrains_Mono']">
              Success Rate
            </div>
          </div>
        </div>
      </div>

      {/* Available Templates Info */}
      <div className="mt-4 p-3 bg-blue-900/20 border border-blue-700 rounded">
        <div className="text-blue-400 text-sm font-['JetBrains_Mono']">
          💡 <strong>Template Types:</strong> React Components, Custom Hooks,
          TypeScript Interfaces, API Endpoints, Void Glass Pages
        </div>
      </div>

      {/* Instructions */}
      <div className="mt-4 p-3 bg-purple-900/20 border border-purple-700 rounded">
        <div className="text-purple-400 text-sm font-['JetBrains_Mono']">
          🚀 <strong>How it works:</strong> Write markdown specification →
          Template engine generates React component → Component integrates automatically
        </div>
      </div>
    </div>
  )
}

export default ComponentFactory